#docker-compose.yml
version: '3.1'

services: 
  cli-consignment:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    ports: 
      - "50051:50051"
    environment: 
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - 'mongo'


  vessel-service:
    build: ./vessel-service
    ports: 
      - "50052:50051"
    environment: 
        MICRO_ADDRESS: ":50051"
        DB_HOST: "localhost:27017"

  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
      - 27017:27017
