#docker-compose.yml
version: '3.1'

services: 
  cli-consignment:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - mongodb
      - vessel-service

  consignment-service:
    build: ./consignment-service
    ports: 
      - "50051:50051"
    environment: 
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
            - mongodb
            - vessel-service


  vessel-service:
    build: ./vessel-service
    ports: 
      - "50052:50051"
    environment: 
        MICRO_ADDRESS: ":50051"
        DB_HOST: "mongodb-service"
    depends_on:
      - mongodb

  mongodb :
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
