#docker-compose.yml
version: '3.1'

services: 
  cli-consignment:
    build: ./consignment-cli

  consignment-service:
    build: ./consignment-service
    ports: 
      - "50051:50051"
    environment: 
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    ports: 
      - "50052:50051"
    environment: 
        MICRO_ADDRESS: ":50051"