// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

package vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	Created              bool      `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*Vessel)(nil), "Vessel")
	proto.RegisterType((*Specification)(nil), "Specification")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor_04ef66862bb50716) }

var fileDescriptor_04ef66862bb50716 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4d, 0x4f, 0xf3, 0x30,
	0x0c, 0xc7, 0x9f, 0x74, 0x5b, 0x5f, 0xfc, 0x68, 0x3b, 0xf8, 0x94, 0x4d, 0xbc, 0x94, 0x9e, 0x76,
	0x40, 0x45, 0x1a, 0x9f, 0x00, 0x21, 0x21, 0xc1, 0x31, 0x93, 0xe0, 0x84, 0xa6, 0x2c, 0x31, 0x2c,
	0xd2, 0xd6, 0x56, 0x6d, 0xd5, 0x8d, 0x6f, 0xc3, 0x47, 0x45, 0x72, 0xd7, 0x41, 0x39, 0x70, 0x8a,
	0xfd, 0xb3, 0xe3, 0xfc, 0xfd, 0x0f, 0x4c, 0x8b, 0x32, 0xaf, 0xf3, 0x9b, 0x86, 0xaa, 0x8a, 0xb6,
	0xc7, 0x23, 0x65, 0x96, 0x7c, 0x0a, 0xf0, 0x9f, 0x19, 0xe0, 0x04, 0x3c, 0x67, 0xa5, 0x88, 0xc5,
	0x3c, 0x52, 0x9e, 0xb3, 0x38, 0x83, 0xd0, 0xe8, 0x42, 0x1b, 0x57, 0x7f, 0x48, 0x2f, 0x16, 0xf3,
	0x91, 0x3a, 0xe5, 0x78, 0x0e, 0xb0, 0xd3, 0x87, 0xd5, 0x9e, 0xdc, 0xfb, 0xa6, 0x96, 0x03, 0xae,
	0x46, 0x3b, 0x7d, 0x78, 0x61, 0x80, 0x08, 0xc3, 0x4c, 0xef, 0x48, 0x0e, 0x79, 0x18, 0xc7, 0x78,
	0x06, 0x91, 0x6e, 0xb4, 0xdb, 0xea, 0xf5, 0x96, 0xe4, 0x28, 0x16, 0xf3, 0x50, 0x7d, 0x03, 0x9c,
	0x42, 0x98, 0xef, 0x33, 0x2a, 0x57, 0xce, 0x4a, 0x9f, 0x6f, 0x05, 0x9c, 0x3f, 0xda, 0xe4, 0x09,
	0xc6, 0xcb, 0x82, 0x8c, 0x7b, 0x73, 0x46, 0xd7, 0x2e, 0xcf, 0x7a, 0xc2, 0xc4, 0x9f, 0xc2, 0xbc,
	0x5f, 0xc2, 0x92, 0x0d, 0x84, 0x8a, 0xaa, 0x22, 0xcf, 0x2a, 0xc2, 0x4b, 0xf0, 0x5b, 0x2b, 0x78,
	0xc8, 0xff, 0x45, 0x90, 0xb6, 0x46, 0xa8, 0x23, 0xc6, 0x2b, 0x08, 0xda, 0xa8, 0x92, 0x5e, 0x3c,
	0xf8, 0xd9, 0xd1, 0x71, 0x94, 0x10, 0x98, 0x92, 0x74, 0x4d, 0x96, 0x4d, 0x08, 0x55, 0x97, 0x2e,
	0x5e, 0x61, 0xdc, 0x36, 0x2f, 0xa9, 0x6c, 0x9c, 0x21, 0xbc, 0x86, 0xf1, 0x83, 0xcb, 0xec, 0xdd,
	0x69, 0xe5, 0x49, 0xda, 0x5b, 0x6b, 0x16, 0xa5, 0x9d, 0xb4, 0xe4, 0x1f, 0x5e, 0x80, 0x7f, 0xcf,
	0x93, 0xb0, 0x7b, 0xb4, 0x57, 0x5f, 0xfb, 0xfc, 0x7d, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x79, 0x85, 0xca, 0xdc, 0xdb, 0x01, 0x00, 0x00,
}
